#pragma once

#ifndef _NTACCESSRIGHTS_
#define _NTACCESSRIGHTS_

#include "NtCommonDefs.h"

extern "C" {

    // typedef DWORD ACCESS_MASK;

    typedef enum _ACCESS_MASK {
        DELETE = 0x00010000L,
        READ_CONTROL = 0x00020000L,
        WRITE_DAC = 0x00040000L,
        WRITE_OWNER = 0x00080000L,
        SYNCHRONIZE = 0x00100000L,

        STANDARD_RIGHTS_REQUIRED = 0x000F0000L,

        STANDARD_RIGHTS_READ = READ_CONTROL,
        STANDARD_RIGHTS_WRITE = READ_CONTROL,
        STANDARD_RIGHTS_EXECUTE = READ_CONTROL,

        STANDARD_RIGHTS_ALL = 0x001F0000L,

        SPECIFIC_RIGHTS_ALL = 0x0000FFFFL
    } ACCESS_MASK;

    typedef enum _DIRECTORY_ACCESS_MASK {
        DIRECTORY_QUERY = 0x0001,
        DIRECTORY_TRAVERSE = 0x0002,
        DIRECTORY_CREATE_OBJECT = 0x0004,
        DIRECTORY_CREATE_SUBDIRECTORY = 0x0008,

        DIRECTORY_ALL_ACCESS = STANDARD_RIGHTS_REQUIRED | 0xF
    } DIRECTORY_ACCESS_MASK;

    // File related
    typedef enum _FILE_ACCESS_MASK {
        FILE_READ_DATA = 0x0001, // file & pipe
        FILE_LIST_DIRECTORY = 0x0001, // directory
        FILE_WRITE_DATA = 0x0002, // file & pipe
        FILE_ADD_FILE = 0x0002, // directory
        FILE_APPEND_DATA = 0x0004, // file
        FILE_ADD_SUBDIRECTORY = 0x0004, // directory
        FILE_CREATE_PIPE_INSTANCE = 0x0004, // named pipe
        FILE_READ_EA = 0x0008, // file & directory
        FILE_WRITE_EA = 0x0010, // file & directory
        FILE_EXECUTE = 0x0020, // file
        FILE_TRAVERSE = 0x0020, // directory
        FILE_DELETE_CHILD = 0x0040, // directory
        FILE_READ_ATTRIBUTES = 0x0080, // all
        FILE_WRITE_ATTRIBUTES = 0x0100, // all

        FILE_ALL_ACCESS = (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF),
        FILE_GENERIC_READ = (STANDARD_RIGHTS_READ | FILE_READ_DATA | FILE_READ_ATTRIBUTES | FILE_READ_EA | SYNCHRONIZE),
        FILE_GENERIC_WRITE = (STANDARD_RIGHTS_WRITE | FILE_WRITE_DATA | FILE_WRITE_ATTRIBUTES | FILE_WRITE_EA |
            FILE_APPEND_DATA | SYNCHRONIZE),
        FILE_GENERIC_EXECUTE = (STANDARD_RIGHTS_EXECUTE | FILE_READ_ATTRIBUTES | FILE_EXECUTE | SYNCHRONIZE)
    } FILE_ACCESS_MASK;

    typedef enum _EVENT_ACCESS_MASK {
        EVENT_MODIFY_STATE = 0x0002,
        EVENT_ALL_ACCESS = ( STANDARD_RIGHTS_REQUIRED |SYNCHRONIZE | 0x3) 
    } EVENT_ACCESS_MASK;

    typedef enum _KEY_ACCESS_MASK {
        KEY_QUERY_VALUE  = 0x0001,
        KEY_SET_VALUE = 0x0002,
        KEY_CREATE_SUB_KEY = 0x0004,
        KEY_ENUMERATE_SUB_KEYS = 0x0008,
        KEY_NOTIFY = 0x0010,
        KEY_CREATE_LINK = 0x0020,
        KEY_WOW64_32KEY = 0x0200,
        KEY_WOW64_64KEY = 0x0100,
        KEY_WOW64_RES = 0x0300,
        
        KEY_READ = (STANDARD_RIGHTS_READ | KEY_QUERY_VALUE | KEY_ENUMERATE_SUB_KEYS | KEY_NOTIFY) & (~SYNCHRONIZE),
        KEY_WRITE = (STANDARD_RIGHTS_WRITE | KEY_SET_VALUE | KEY_CREATE_SUB_KEY) & (~SYNCHRONIZE),
        KEY_EXECUTE = KEY_READ & (~SYNCHRONIZE),
        KEY_ALL_ACCESS = (STANDARD_RIGHTS_ALL | KEY_QUERY_VALUE | KEY_SET_VALUE | KEY_CREATE_SUB_KEY |
            KEY_ENUMERATE_SUB_KEYS | KEY_NOTIFY | KEY_CREATE_LINK) & (~SYNCHRONIZE)
    } KEY_ACCESS_MASK;

    typedef enum _MUTANT_ACCESS_MASK {
        MUTANT_QUERY_STATE = 0x0001,
        MUTANT_ALL_ACCESS = (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | MUTANT_QUERY_STATE)
    } MUTANT_ACCESS_MASK;

    typedef enum _PROCESS_ACCESS_MASK {
        PROCESS_TERMINATE = 0x0001,
        PROCESS_CREATE_THREAD = 0x0002,
        PROCESS_SET_SESSIONID = 0x0004,
        PROCESS_VM_OPERATION = 0x0008,
        PROCESS_VM_READ = 0x0010,
        PROCESS_VM_WRITE = 0x0020,
        PROCESS_DUP_HANDLE = 0x0040,
        PROCESS_CREATE_PROCESS = 0x0080,
        PROCESS_SET_QUOTA = 0x0100,
        PROCESS_SET_INFORMATION = 0x0200,
        PROCESS_QUERY_INFORMATION = 0x0400,
        PROCESS_SUSPEND_RESUME = 0x0800,
        PROCESS_QUERY_LIMITED_INFORMATION = 0x1000,
        PROCESS_SET_LIMITED_INFORMATION = 0x2000,
        PROCESS_ALL_ACCESS = STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0xFFFF
    } PROCESS_ACCESS_MASK;

    typedef enum _SEMAPHORE_ACCESS_MASK {
        SEMAPHORE_MODIFY_STATE = 0x0002,
        SEMAPHORE_ALL_ACCESS = (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x3)
    }SEMAPHORE_ACCESS_MASK;

    typedef enum _THREAD_ACCESS_MASK {
        THREAD_TERMINATE = 0x0001,
        THREAD_SUSPEND_RESUME = 0x0002,
        THREAD_GET_CONTEXT = 0x0008,
        THREAD_SET_CONTEXT = 0x0010,
        THREAD_QUERY_INFORMATION = 0x0040,
        THREAD_SET_INFORMATION = 0x0020,
        THREAD_SET_THREAD_TOKEN = 0x0080,
        THREAD_IMPERSONATE = 0x0100,
        THREAD_DIRECT_IMPERSONATION = 0x0200,
        THREAD_SET_LIMITED_INFORMATION = 0x0400,  // winnt
        THREAD_QUERY_LIMITED_INFORMATION = 0x0800,  // winnt
        THREAD_RESUME = 0x1000,  // winnt
        THREAD_ALL_ACCESS = STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0xFFFF
    } THREAD_ACCESS_MASK;

    typedef enum _TIMER_ACCESS_MASK {
        TIMER_QUERY_STATE = 0x0001,
        TIMER_MODIFY_STATE = 0x0002,
        TIMER_ALL_ACCESS = (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | TIMER_QUERY_STATE | TIMER_MODIFY_STATE)
    } TIMER_ACCESS_MASK;
}

#endif